language: erlang
otp_release:
  - R16B
  - R15B03
  - R15B02
  - R15B01
  - R15B
script: "make rebuild"
branches:
  only:
    - master
notifications:
  email:
    - core@erlware.org
  irc: "irc.freenode.org#erlware"
    